/**
 *
 * $Id$
 */
package com.tum.vsms.Location.Location.validation;

import com.tum.vsms.Location.Location.Address;

/**
 * A sample validator interface for {@link com.tum.vsms.Location.Location.Location}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LocationValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateCode(String value);
	boolean validateName(String value);
	boolean validateLatitude(double value);
	boolean validateLongitude(double value);
	boolean validateAddress(Address value);
}
