/**
 *
 * $Id$
 */
package com.tum.vsms.Payment.Payment.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link com.tum.vsms.Payment.Payment.Invoice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InvoiceValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateCustomer_name(String value);
	boolean validateCustomer_address(String value);
	boolean validateDuration(String value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validateTotalCost(double value);
}
