/**
 *
 * $Id$
 */
package com.tum.vsms.Reservation.Reservation.validation;

import com.tum.vsms.Reservation.Reservation.Customer;
import com.tum.vsms.Reservation.Reservation.Location;
import com.tum.vsms.Reservation.Reservation.Vehicle;

import java.util.Date;

/**
 * A sample validator interface for {@link com.tum.vsms.Reservation.Reservation.Reservation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReservationValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateTotalCost(double value);
	boolean validateStart_time(Date value);
	boolean validateEnd_time(String value);
	boolean validateStart_date(Date value);
	boolean validateEnd_date(Date value);
	boolean validateRefuelEnabled(boolean value);
	boolean validateChargingEnabled(boolean value);
	boolean validateDuration(double value);
	boolean validateCustomer(Customer value);
	boolean validateVehicle(Vehicle value);
	boolean validateStart_location(Location value);
	boolean validateEnd_location(Location value);
}
