/**
 *
 * $Id$
 */
package com.tum.vsms.model.User.validation;

import com.tum.vsms.model.User.Level;

/**
 * A sample validator interface for {@link com.tum.vsms.model.User.Operative}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperativeValidator {
	boolean validate();

	boolean validatePosition(Level value);
}
