/**
 *
 * $Id$
 */
package com.tum.vsms.model.Vehicle.validation;

import com.tum.vsms.model.Vehicle.Position;
import com.tum.vsms.model.Vehicle.VehicleType;

/**
 * A sample validator interface for {@link com.tum.vsms.model.Vehicle.Vehicle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VehicleValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateVehicleType(VehicleType value);
	boolean validateLicense(String value);
	boolean validateRegistration(String value);
	boolean validateBrand(String value);
	boolean validateModel(String value);
	boolean validateYear(String value);
	boolean validateColor(String value);
	boolean validateAvailableSeat(int value);
	boolean validateAdditionalSeat(int value);
	boolean validateVehicleId(String value);
	boolean validatePosition(Position value);
}
